# Generated by Django 3.1.3 on 2020-12-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_auto_20201224_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('emergency medecine specialist', 'Emergency Medecine Specialists'), ('allergist', 'Allergists'), ('anesthesiologist', 'Anesthesiologist')], max_length=200),
        ),
    ]
