# Generated by Django 3.1.3 on 2020-12-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('symptom', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('admit_to', models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('emergency medecine specialist', 'Emergency Medecine Specialists'), ('allergist', 'Allergists'), ('anesthesiologist', 'Anesthesiologist')], max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
