# Generated by Django 3.1.3 on 2020-12-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_auto_20201225_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
