# Generated by Django 3.1.3 on 2020-12-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_patientmodel_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_charge', models.IntegerField()),
                ('doctor_fee', models.IntegerField()),
                ('medecine_cost', models.IntegerField()),
                ('Other_charge', models.IntegerField()),
            ],
        ),
    ]
