# Generated by Django 3.1.3 on 2020-12-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0012_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
