# Generated by Django 3.1.3 on 2020-12-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0013_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('patient_id', models.PositiveIntegerField(null=True)),
                ('doctor_id', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
