# Generated by Django 3.1.3 on 2020-12-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
