# Generated by Django 3.1.3 on 2020-12-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0016_auto_20201228_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
