# Generated by Django 3.1.3 on 2020-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0019_auto_20201230_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
