# Generated by Django 3.1.3 on 2020-12-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0021_patientmodel_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='doctor_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
