# Generated by Django 3.1.3 on 2021-01-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0022_patientmodel_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_charge', models.IntegerField()),
                ('doctor_fee', models.IntegerField()),
                ('medecine_cost', models.IntegerField()),
                ('Other_charge', models.IntegerField()),
                ('patient_id', models.PositiveIntegerField()),
            ],
        ),
    ]
