# Generated by Django 3.1.3 on 2021-01-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0023_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
    ]
